language: cpp
addons:
  apt:
    packages:
    - gfortran
    - libhdf5-serial-dev
    - liblapack-dev
    - python-numpy
    - swig
script:
#  - ./autogen.sh --enable-shared --with-python
  - ./autogen.sh --enable-shared
  - make
#  - PYTHONPATH=src/libs/python:src/libs/python/.libs python -c 'import scuff'
