language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libhdf5-serial-dev liblapack-dev python-numpy swig
script: ./autogen.sh --enable-shared --with-python && make
